name: release
on:
  push:
    branches: [master]

jobs:
  # build:
  #   uses: ./.github/workflows/build.yml

  release:
    name: release
    runs-on: ubuntu-latest
    # needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      # - name: Download artifact
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: output-pdf
      - name: Setup git
        run: |
          git config --global user.email "{{ secrets.GIT_MAIL }}"
          git config --global user.name "{{ secrets.GIT_USER }}"
      - name: Create a tag
        run: |
          tag=$(date '+%Y-%m-%dT%H%M%S')
          git tag -a "$tag" -m "Release $tag"
          git push origin --follow-tags
      - name: Create changelog
        run: |
          echo "## Changes since last release" > changelog.md
          git log --pretty=format:"%h %s" $(git describe --tags --abbrev=0)..HEAD >> changelog.md
      - name: Create a release
        uses: softprops/action-gh-release@v2
        with:
          body_path: changelog.md
          files: |
            ${{ github.workspace }}/output.pdf
